name: Auto-update README and move newly added solution files during PR checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["main"]

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

jobs:
  update_readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout source branch of current PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GIT_PAT }}

      - name: Check if latest commit is not [auto]-based before proceeding
        id: latest_commit
        run: |
          COMMIT_MSG="$(git log -1 --pretty=format:%s)"

          if [[ "$COMMIT_MSG" == '[auto]'* ]]; then
            echo "Latest commit is [auto]-based, ending workflow..."
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "Latest commit is NOT [auto]-based, resuming workflow..."
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Install the latest version of uv
        if: steps.latest_commit.outputs.should_skip == 'false'
        uses: astral-sh/setup-uv@v6

      - name: Setup Python via uv
        if: steps.latest_commit.outputs.should_skip == 'false'
        run: uv python install ${{ matrix.python-version }}

      - name: Setup dependencies via uv
        if: steps.latest_commit.outputs.should_skip == 'false'
        run: uv sync --directory ./.github

      - name: Move solution files to their respective folders via lc_move.py
        if: steps.latest_commit.outputs.should_skip == 'false'
        id: move_step
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python ./scripts/lc_move.py | tee output.log
          echo "files_moved=$(grep '\[END\]' output.log | grep -o '[0-9]\+')" >> $GITHUB_OUTPUT
          rm output.log

      - name: Update progress chart and README via lc_markdown.py
        if: steps.latest_commit.outputs.should_skip == 'false' && steps.move_step.outputs.files_moved != '0'
        run: |
          export PYTHONPATH=$GITHUB_WORKSPACE
          python ./scripts/lc_markdown.py

      - name: Check for changed files
        if: steps.latest_commit.outputs.should_skip == 'false' && steps.move_step.outputs.files_moved != '0'
        run: git status

      - name: Stage changed files
        if: steps.latest_commit.outputs.should_skip == 'false' && steps.move_step.outputs.files_moved != '0'
        run: git add .

      - name: Commit changed files
        if: steps.latest_commit.outputs.should_skip == 'false' && steps.move_step.outputs.files_moved != '0'
        run: |
          if ! git diff --cached --quiet; then
            git config user.name $GIT_USERNAME
            git config user.email $GIT_EMAIL
            git commit -m "[auto] update README and move solution files (R.N: ${{ github.run_number }})" \
                      -m "Push commit: ${{ github.sha }} " \
                      -m "Files moved: ${{ steps.move_step.outputs.files_moved }}" \
                      -m "Workflow: ${{ github.workflow }}" \
                      -m "Triggered on: ${{ github.event_name }}" \
                      -m "Run Link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            echo "No changes to commit"
          fi

      - name: Push updated README and move solution files to source branch
        if: steps.latest_commit.outputs.should_skip == 'false' && steps.move_step.outputs.files_moved != '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_PAT }}
          branch: ${{ github.head_ref }}
